services:
  repositories.UserRepository:
    class: Rocket/User/infrastructure/MysqlUserRepository

  usecase.UserCreator:
    class: Rocket/User/application/UserCreator
    arguments: ['@repositories.UserRepository']

  controllers.AuthenticationController:
    class: Backend/controllers/authentication
    arguments: ['@usecase.UserCreator']

