services:
  repositories.UserRepository:
    class: Rocket/User/application/MysqlUserRepository

  controllers.AuthenticationController:
    class: Backend/controllers/authentication
    arguments: ['@repositories.UserRepository']
