services:
  repositories.UserRepository:
    class: infrastructure/repositories/MysqlUserRepository

  usecase.UserCreator:
    class: application/User/UserCreator
    arguments: ['@repositories.UserRepository']

  controllers.AuthenticationController:
    class: infrastructure/controllers/authentication
    arguments: ['@usecase.UserCreator']

