services:
  repositories.UserRepository:
    class: infrastructure/repositories/MysqlUserRepository

  usecase.UserCases:
    class: application/UserUseCases
    arguments: ['@repositories.UserRepository']

  controllers.AuthenticationController:
    class: infrastructure/controllers/authentication
    arguments: ['@usecase.UserCases']

