paths:
  /api/auth/register: # path of the user from your endpoint
    post: # endpoint request type (post request)
      tags: # Tag property
        - Authentication # Value of the tag
      summary: Register a new User
      consumes:
        - application/json
      parameters: # request parameters
        - in: body # request body
          name: body # name of request, can be any name
          description: It enables a user to create an account
          required: true # can also be true depending on user preference
          schema: # Schema definition
            $ref: '#/definitions/signUp'
      responses: # server responses
        200:
          description: An object with user details
definitions: # Schema defination for request body
  signUp:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
